export const SAMPLES_PER_BEAT = 64;
export const NOTE_SAMPLES_PER_BEAT = 256;
export const POLYLINE_STEP = 1;
export const THICKNESS = 0.5;
export const TILE_MIN = 0;
export const TILE_MAX = 9;
export const TILE_COUNT = 10;
export const GENERATED_VELOCITY = 3;
export const MIN_NOTE_DURATION = 1 / 4096;
