export const IPC_CHANNELS = {
  sendGeneratedPreview: 'bridge:send-generated-preview',
  requestAppVersion: 'bridge:request-app-version',
  requestLiveTempo: 'bridge:request-live-tempo',
  liveTempoUpdate: 'live:tempo-update',
  openPreviewWindow: 'preview:open-window',
  pushPreviewWindowState: 'preview:push-state',
  previewWindowStateUpdate: 'preview:state-update',
  requestPreviewWindowState: 'preview:request-state',
  requestPreviewWindowVisibility: 'preview:request-window-visibility',
  previewWindowVisibilityUpdate: 'preview:window-visibility-update',
  mainWindowCloseRequest: 'app:main-window-close-request',
  mainWindowRackFileMenuRequest: 'app:main-window-rack-file-menu-request',
  confirmMainWindowClose: 'app:confirm-main-window-close',
  pushMainWindowDocumentState: 'app:push-main-window-document-state',
  openExternal: 'bridge:open-external',
  savePresetFile: 'preset:save-file',
  saveRackFile: 'preset:save-rack-file',
  createPresetFolder: 'preset:create-folder',
  renamePresetFolder: 'preset:rename-folder',
  listPresetBrowserTree: 'preset:list-browser-tree',
  showPresetEntryInFolder: 'preset:show-entry-in-folder',
  showPresetsRootInFolder: 'preset:show-root-in-folder',
  deletePresetEntry: 'preset:delete-entry',
  readPresetEntry: 'preset:read-entry',
} as const;
